// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/auth.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterDeviceRequest contains device registration information
type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterDeviceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// RegisterDeviceResponse contains the registration result and configuration
type RegisterDeviceResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token               string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ServerKey           string                 `protobuf:"bytes,3,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
	Endpoint            string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,5,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	PersistentKeepalive int32                  `protobuf:"varint,6,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	DnsServers          []string               `protobuf:"bytes,7,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	ForwardingRules     []string               `protobuf:"bytes,8,rep,name=forwarding_rules,json=forwardingRules,proto3" json:"forwarding_rules,omitempty"`
	Routes              []string               `protobuf:"bytes,9,rep,name=routes,proto3" json:"routes,omitempty"`
	Mtu                 int32                  `protobuf:"varint,10,opt,name=mtu,proto3" json:"mtu,omitempty"`
	ListenPort          int32                  `protobuf:"varint,11,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterDeviceResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterDeviceResponse) GetServerKey() string {
	if x != nil {
		return x.ServerKey
	}
	return ""
}

func (x *RegisterDeviceResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterDeviceResponse) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *RegisterDeviceResponse) GetPersistentKeepalive() int32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

func (x *RegisterDeviceResponse) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *RegisterDeviceResponse) GetForwardingRules() []string {
	if x != nil {
		return x.ForwardingRules
	}
	return nil
}

func (x *RegisterDeviceResponse) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RegisterDeviceResponse) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *RegisterDeviceResponse) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

// RefreshTokenRequest contains token refresh information
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RefreshTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RefreshTokenResponse contains the token refresh result
type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// GetConfigurationRequest contains configuration retrieval information
type GetConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetConfigurationRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetConfigurationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// GetConfigurationResponse contains the device configuration
type GetConfigurationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceConfig    *DeviceConfiguration   `protobuf:"bytes,1,opt,name=device_config,json=deviceConfig,proto3" json:"device_config,omitempty"`
	ServerConfig    *ServerConfiguration   `protobuf:"bytes,2,opt,name=server_config,json=serverConfig,proto3" json:"server_config,omitempty"`
	NetworkConfig   *NetworkConfiguration  `protobuf:"bytes,3,opt,name=network_config,json=networkConfig,proto3" json:"network_config,omitempty"`
	ExitNodeConfig  *ExitNodeConfiguration `protobuf:"bytes,4,opt,name=exit_node_config,json=exitNodeConfig,proto3" json:"exit_node_config,omitempty"`
	UpdateAvailable bool                   `protobuf:"varint,5,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`
	UpdateVersion   string                 `protobuf:"bytes,6,opt,name=update_version,json=updateVersion,proto3" json:"update_version,omitempty"`
	UpdateUrl       string                 `protobuf:"bytes,7,opt,name=update_url,json=updateUrl,proto3" json:"update_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetConfigurationResponse) GetDeviceConfig() *DeviceConfiguration {
	if x != nil {
		return x.DeviceConfig
	}
	return nil
}

func (x *GetConfigurationResponse) GetServerConfig() *ServerConfiguration {
	if x != nil {
		return x.ServerConfig
	}
	return nil
}

func (x *GetConfigurationResponse) GetNetworkConfig() *NetworkConfiguration {
	if x != nil {
		return x.NetworkConfig
	}
	return nil
}

func (x *GetConfigurationResponse) GetExitNodeConfig() *ExitNodeConfiguration {
	if x != nil {
		return x.ExitNodeConfig
	}
	return nil
}

func (x *GetConfigurationResponse) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *GetConfigurationResponse) GetUpdateVersion() string {
	if x != nil {
		return x.UpdateVersion
	}
	return ""
}

func (x *GetConfigurationResponse) GetUpdateUrl() string {
	if x != nil {
		return x.UpdateUrl
	}
	return ""
}

// DeviceConfiguration contains device-specific network settings
type DeviceConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ListenPort    int32                  `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Mtu           int32                  `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Dns           []string               `protobuf:"bytes,4,rep,name=dns,proto3" json:"dns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfiguration) Reset() {
	*x = DeviceConfiguration{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfiguration) ProtoMessage() {}

func (x *DeviceConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfiguration.ProtoReflect.Descriptor instead.
func (*DeviceConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceConfiguration) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *DeviceConfiguration) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *DeviceConfiguration) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *DeviceConfiguration) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

// ServerConfiguration contains server connection settings
type ServerConfiguration struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Endpoint            string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Port                int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	PublicKey           string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	PersistentKeepalive int32                  `protobuf:"varint,5,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerConfiguration) Reset() {
	*x = ServerConfiguration{}
	mi := &file_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfiguration) ProtoMessage() {}

func (x *ServerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfiguration.ProtoReflect.Descriptor instead.
func (*ServerConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ServerConfiguration) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ServerConfiguration) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerConfiguration) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ServerConfiguration) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *ServerConfiguration) GetPersistentKeepalive() int32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

// NetworkConfiguration contains network routing and firewall settings
type NetworkConfiguration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Routes          []string               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	ForwardingRules []string               `protobuf:"bytes,2,rep,name=forwarding_rules,json=forwardingRules,proto3" json:"forwarding_rules,omitempty"`
	FirewallRules   []string               `protobuf:"bytes,3,rep,name=firewall_rules,json=firewallRules,proto3" json:"firewall_rules,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkConfiguration) Reset() {
	*x = NetworkConfiguration{}
	mi := &file_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfiguration) ProtoMessage() {}

func (x *NetworkConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfiguration.ProtoReflect.Descriptor instead.
func (*NetworkConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkConfiguration) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NetworkConfiguration) GetForwardingRules() []string {
	if x != nil {
		return x.ForwardingRules
	}
	return nil
}

func (x *NetworkConfiguration) GetFirewallRules() []string {
	if x != nil {
		return x.FirewallRules
	}
	return nil
}

// ExitNodeConfiguration contains exit node settings
type ExitNodeConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ExitRoutes    []string               `protobuf:"bytes,2,rep,name=exit_routes,json=exitRoutes,proto3" json:"exit_routes,omitempty"`
	ExitDns       []string               `protobuf:"bytes,3,rep,name=exit_dns,json=exitDns,proto3" json:"exit_dns,omitempty"`
	AllowLan      bool                   `protobuf:"varint,4,opt,name=allow_lan,json=allowLan,proto3" json:"allow_lan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitNodeConfiguration) Reset() {
	*x = ExitNodeConfiguration{}
	mi := &file_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitNodeConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitNodeConfiguration) ProtoMessage() {}

func (x *ExitNodeConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitNodeConfiguration.ProtoReflect.Descriptor instead.
func (*ExitNodeConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ExitNodeConfiguration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ExitNodeConfiguration) GetExitRoutes() []string {
	if x != nil {
		return x.ExitRoutes
	}
	return nil
}

func (x *ExitNodeConfiguration) GetExitDns() []string {
	if x != nil {
		return x.ExitDns
	}
	return nil
}

func (x *ExitNodeConfiguration) GetAllowLan() bool {
	if x != nil {
		return x.AllowLan
	}
	return false
}

// StartDeviceFlowRequest initiates a device authorization flow
type StartDeviceFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDeviceFlowRequest) Reset() {
	*x = StartDeviceFlowRequest{}
	mi := &file_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeviceFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeviceFlowRequest) ProtoMessage() {}

func (x *StartDeviceFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeviceFlowRequest.ProtoReflect.Descriptor instead.
func (*StartDeviceFlowRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *StartDeviceFlowRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// StartDeviceFlowResponse contains device flow information
type StartDeviceFlowResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceCode      string                 `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	UserCode        string                 `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	VerificationUri string                 `protobuf:"bytes,3,opt,name=verification_uri,json=verificationUri,proto3" json:"verification_uri,omitempty"`
	ExpiresIn       int32                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Interval        int32                  `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartDeviceFlowResponse) Reset() {
	*x = StartDeviceFlowResponse{}
	mi := &file_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeviceFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeviceFlowResponse) ProtoMessage() {}

func (x *StartDeviceFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeviceFlowResponse.ProtoReflect.Descriptor instead.
func (*StartDeviceFlowResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *StartDeviceFlowResponse) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *StartDeviceFlowResponse) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *StartDeviceFlowResponse) GetVerificationUri() string {
	if x != nil {
		return x.VerificationUri
	}
	return ""
}

func (x *StartDeviceFlowResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *StartDeviceFlowResponse) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

// PollDeviceFlowRequest polls for device flow completion
type PollDeviceFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceCode    string                 `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollDeviceFlowRequest) Reset() {
	*x = PollDeviceFlowRequest{}
	mi := &file_proto_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollDeviceFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollDeviceFlowRequest) ProtoMessage() {}

func (x *PollDeviceFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollDeviceFlowRequest.ProtoReflect.Descriptor instead.
func (*PollDeviceFlowRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{12}
}

func (x *PollDeviceFlowRequest) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

// PollDeviceFlowResponse indicates device flow completion status
type PollDeviceFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollDeviceFlowResponse) Reset() {
	*x = PollDeviceFlowResponse{}
	mi := &file_proto_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollDeviceFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollDeviceFlowResponse) ProtoMessage() {}

func (x *PollDeviceFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollDeviceFlowResponse.ProtoReflect.Descriptor instead.
func (*PollDeviceFlowResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{13}
}

func (x *PollDeviceFlowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\x04grpc\"p\n" +
	"\x15RegisterDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\xee\x02\n" +
	"\x16RegisterDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"server_key\x18\x03 \x01(\tR\tserverKey\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x05 \x03(\tR\n" +
	"allowedIps\x121\n" +
	"\x14persistent_keepalive\x18\x06 \x01(\x05R\x13persistentKeepalive\x12\x1f\n" +
	"\vdns_servers\x18\a \x03(\tR\n" +
	"dnsServers\x12)\n" +
	"\x10forwarding_rules\x18\b \x03(\tR\x0fforwardingRules\x12\x16\n" +
	"\x06routes\x18\t \x03(\tR\x06routes\x12\x10\n" +
	"\x03mtu\x18\n" +
	" \x01(\x05R\x03mtu\x12\x1f\n" +
	"\vlisten_port\x18\v \x01(\x05R\n" +
	"listenPort\"H\n" +
	"\x13RefreshTokenRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"F\n" +
	"\x14RefreshTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"L\n" +
	"\x17GetConfigurationRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x95\x03\n" +
	"\x18GetConfigurationResponse\x12>\n" +
	"\rdevice_config\x18\x01 \x01(\v2\x19.grpc.DeviceConfigurationR\fdeviceConfig\x12>\n" +
	"\rserver_config\x18\x02 \x01(\v2\x19.grpc.ServerConfigurationR\fserverConfig\x12A\n" +
	"\x0enetwork_config\x18\x03 \x01(\v2\x1a.grpc.NetworkConfigurationR\rnetworkConfig\x12E\n" +
	"\x10exit_node_config\x18\x04 \x01(\v2\x1b.grpc.ExitNodeConfigurationR\x0eexitNodeConfig\x12)\n" +
	"\x10update_available\x18\x05 \x01(\bR\x0fupdateAvailable\x12%\n" +
	"\x0eupdate_version\x18\x06 \x01(\tR\rupdateVersion\x12\x1d\n" +
	"\n" +
	"update_url\x18\a \x01(\tR\tupdateUrl\"x\n" +
	"\x13DeviceConfiguration\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\x05R\n" +
	"listenPort\x12\x10\n" +
	"\x03mtu\x18\x03 \x01(\x05R\x03mtu\x12\x10\n" +
	"\x03dns\x18\x04 \x03(\tR\x03dns\"\xb8\x01\n" +
	"\x13ServerConfiguration\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\x121\n" +
	"\x14persistent_keepalive\x18\x05 \x01(\x05R\x13persistentKeepalive\"\x80\x01\n" +
	"\x14NetworkConfiguration\x12\x16\n" +
	"\x06routes\x18\x01 \x03(\tR\x06routes\x12)\n" +
	"\x10forwarding_rules\x18\x02 \x03(\tR\x0fforwardingRules\x12%\n" +
	"\x0efirewall_rules\x18\x03 \x03(\tR\rfirewallRules\"\x8a\x01\n" +
	"\x15ExitNodeConfiguration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vexit_routes\x18\x02 \x03(\tR\n" +
	"exitRoutes\x12\x19\n" +
	"\bexit_dns\x18\x03 \x03(\tR\aexitDns\x12\x1b\n" +
	"\tallow_lan\x18\x04 \x01(\bR\ballowLan\"5\n" +
	"\x16StartDeviceFlowRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\xbd\x01\n" +
	"\x17StartDeviceFlowResponse\x12\x1f\n" +
	"\vdevice_code\x18\x01 \x01(\tR\n" +
	"deviceCode\x12\x1b\n" +
	"\tuser_code\x18\x02 \x01(\tR\buserCode\x12)\n" +
	"\x10verification_uri\x18\x03 \x01(\tR\x0fverificationUri\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\x05R\binterval\"8\n" +
	"\x15PollDeviceFlowRequest\x12\x1f\n" +
	"\vdevice_code\x18\x01 \x01(\tR\n" +
	"deviceCode\"2\n" +
	"\x16PollDeviceFlowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x91\x03\n" +
	"\vAuthService\x12K\n" +
	"\x0eRegisterDevice\x12\x1b.grpc.RegisterDeviceRequest\x1a\x1c.grpc.RegisterDeviceResponse\x12E\n" +
	"\fRefreshToken\x12\x19.grpc.RefreshTokenRequest\x1a\x1a.grpc.RefreshTokenResponse\x12Q\n" +
	"\x10GetConfiguration\x12\x1d.grpc.GetConfigurationRequest\x1a\x1e.grpc.GetConfigurationResponse\x12N\n" +
	"\x0fStartDeviceFlow\x12\x1c.grpc.StartDeviceFlowRequest\x1a\x1d.grpc.StartDeviceFlowResponse\x12K\n" +
	"\x0ePollDeviceFlow\x12\x1b.grpc.PollDeviceFlowRequest\x1a\x1c.grpc.PollDeviceFlowResponseB\x1fZ\x1dwantastic-agent/internal/grpcb\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_auth_proto_goTypes = []any{
	(*RegisterDeviceRequest)(nil),    // 0: grpc.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),   // 1: grpc.RegisterDeviceResponse
	(*RefreshTokenRequest)(nil),      // 2: grpc.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),     // 3: grpc.RefreshTokenResponse
	(*GetConfigurationRequest)(nil),  // 4: grpc.GetConfigurationRequest
	(*GetConfigurationResponse)(nil), // 5: grpc.GetConfigurationResponse
	(*DeviceConfiguration)(nil),      // 6: grpc.DeviceConfiguration
	(*ServerConfiguration)(nil),      // 7: grpc.ServerConfiguration
	(*NetworkConfiguration)(nil),     // 8: grpc.NetworkConfiguration
	(*ExitNodeConfiguration)(nil),    // 9: grpc.ExitNodeConfiguration
	(*StartDeviceFlowRequest)(nil),   // 10: grpc.StartDeviceFlowRequest
	(*StartDeviceFlowResponse)(nil),  // 11: grpc.StartDeviceFlowResponse
	(*PollDeviceFlowRequest)(nil),    // 12: grpc.PollDeviceFlowRequest
	(*PollDeviceFlowResponse)(nil),   // 13: grpc.PollDeviceFlowResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	6,  // 0: grpc.GetConfigurationResponse.device_config:type_name -> grpc.DeviceConfiguration
	7,  // 1: grpc.GetConfigurationResponse.server_config:type_name -> grpc.ServerConfiguration
	8,  // 2: grpc.GetConfigurationResponse.network_config:type_name -> grpc.NetworkConfiguration
	9,  // 3: grpc.GetConfigurationResponse.exit_node_config:type_name -> grpc.ExitNodeConfiguration
	0,  // 4: grpc.AuthService.RegisterDevice:input_type -> grpc.RegisterDeviceRequest
	2,  // 5: grpc.AuthService.RefreshToken:input_type -> grpc.RefreshTokenRequest
	4,  // 6: grpc.AuthService.GetConfiguration:input_type -> grpc.GetConfigurationRequest
	10, // 7: grpc.AuthService.StartDeviceFlow:input_type -> grpc.StartDeviceFlowRequest
	12, // 8: grpc.AuthService.PollDeviceFlow:input_type -> grpc.PollDeviceFlowRequest
	1,  // 9: grpc.AuthService.RegisterDevice:output_type -> grpc.RegisterDeviceResponse
	3,  // 10: grpc.AuthService.RefreshToken:output_type -> grpc.RefreshTokenResponse
	5,  // 11: grpc.AuthService.GetConfiguration:output_type -> grpc.GetConfigurationResponse
	11, // 12: grpc.AuthService.StartDeviceFlow:output_type -> grpc.StartDeviceFlowResponse
	13, // 13: grpc.AuthService.PollDeviceFlow:output_type -> grpc.PollDeviceFlowResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
